<?php if ( ! defined('PUKKA_VERSION')) exit('No direct script access allowed');


add_filter('pukka_add_theme_options', 'pukka_theme_options', 1, 1);
function pukka_theme_options($pukka_theme_option_pages){

	// font list and font effects
	include_once(PUKKA_DIR . '/util/init-theme-default-values.php');

	$pukka_theme_option_pages = array();

	$tmp = json_decode($font_list, true);
	$fonts = array();

	global $theme_style_settings;
	$color_schemes = array();


	foreach($theme_style_settings as $k => $v){
		$string = explode('_', $k);
		$string = implode(' ', $string);
		$color_schemes[$k] = $string;
	}

	foreach ($tmp as $k => $v) {
		$fonts[$v['css-name']] = $v['font-name'];
	}

	$pukka_theme_option_pages['pukka_theme_settings_page'] = array(
		'page_title' => 'Theme Settings',
		'menu_title' => 'Theme Settings',
		'page_description' => 'Control and configure UberShop Theme.<br /> If you have any issues please go through Documentation or contact our support team.',
		'page_slug' => 'pukka_theme_settings_page',
		'parent_page_slug' => false,
		'tabs' => array(
			array(
				'title' => __('General settings', 'pukka'),
				'icon' => 'fa-cogs',
				'fields' => array(
					array('title' => __('Logo', 'pukka'),
						'desc' => __('Upload your logo. Ideal height should be 160px or more.', 'pukka'),
						'type' => 'file',
						'id' => 'logo_img_id',
					),
					array('title' => __('Plain text logo', 'pukka'),
						'desc' => __('Insert text which will be displayed if image logo is missing. Default is Site Title.', 'pukka'),
						'type' => 'text',
						'id' => 'text_logo',
					),
					array('title' => __('Plain text logo color', 'pukka'),
						'desc' => __('Color of the text logo which is displayed if image logo is missing.', 'pukka'),
						'type' => 'color-picker',
						'id' => 'text_logo_color',
						'default' => '#666666',
						'reset' => true,
					),
					array('title' => __('Logo for Mobile Menu', 'pukka'),
						'desc' => __('Logo image for Mobile Menu. Maximum/Ideal height is 36px.', 'pukka'),
						'type' => 'file',
						'id' => 'responsive_logo_img_id',
					),
					array('title' => __('Favicon', 'pukka'),
						'desc' => __('Upload your favicon image. Image pixel dimension must be in square aspect ratio (meaning height must be equal to the width). <br />Acceptable dimensions: mimumum 32x32px, maximum 64x64px.', 'pukka'),
						'type' => 'file',
						'id' => 'favicon_id',
					),
					array('title' => __('Analytics code', 'pukka'),
						'desc' => __('Paste your tracking code here. <br />(Google Analytics, AWStats, Piwick, Statcounter, ...).', 'pukka'),
						'type' => 'textarea',
						'id' => 'analytics_code',
					),
					array('title' => __('Single author site', 'pukka'),
						'desc' => __('Select this feature in order to hide author\'s name from specific pages and post categories. ', 'pukka'),
						'type' => 'checkbox',
						'id' => 'single_author_site',
					),
					array('title' => __('Disable page builder HTML editor', 'pukka'),
					      'desc' => __('Check this if you experience problems with using HTML editor in page builder elements.', 'pukka'),
					      'type' => 'checkbox',
					      'id' => 'page_builder_tinymce_disable',
					      'reset' => true,
					),
					array('title' => __('Default page width', 'pukka'),
						'desc' => __('Choose do you want your website to display boxed pages, or full width.', 'pukka'),
						'type' => 'select',
						'id' => 'default_pages_width',
						'reset' => true,
						'options' => array('boxed' => 'Boxed', 'full' => 'Full width'),
						'no_default_text' => true,
						'default' => 'boxed'
					),
				),
			), // end tab General Settings
			array(
				'title' => __('Header and Footer', 'pukka'),
				'icon' => 'fa-list',
				'fields' => array(
					array('title' => __('Enable secondary menu', 'pukka'),
					      'desc' => __('Select this feature in order to enable secondary menu.', 'pukka'),
					      'type' => 'checkbox',
					      'id' => 'enable_secondary_menu',
					      'reset' => true,
					),
					array('title' => __('Secondary menu text', 'pukka'),
					      'desc' => __('Enter secondary menu text here.', 'pukka'),
					      'type' => 'textarea',
					      'id' => 'secondary_menu_text',
					),
					array('title' => __('Enable footer menu', 'pukka'),
					      'desc' => __('Select this feature in order to enable footer menu.', 'pukka'),
					      'type' => 'checkbox',
					      'id' => 'enable_footer_menu',
					      'reset' => true,
					),
					array('title' => __('Footer menu text', 'pukka'),
					      'desc' => __('Enter footer menu text here.', 'pukka'),
					      'type' => 'textarea',
					      'id' => 'footer_menu_text',
					),
				)
			), // end tab Header and footer
			array(
				'title' => __('Posts', 'pukka'),
				'icon' => '',
				'fields' => array(
					array('title' => __('Number of posts per row', 'pukka'),
					      'desc' => __('Number of posts per row for category, tags, search and date archives.', 'pukka'),
					      'type' => 'select',
					      'subtype' => 'range',
					      'min' => 1,
					      'max' => 6,
					      'id' => 'posts_col_no',
					      'reset' => true,
					      'default' => 1,
					),
					array('title' => __('Use page builder in posts', 'pukka'),
					      'desc' => __('Select this feature in order to enable using page builder in posts.', 'pukka'),
					      'type' => 'checkbox',
					      'id' => 'post_page_builder',
					      'reset' => true,
					),
				),
			), // end tab Single
			array(
				'title' => __('Shop', 'pukka'),
				'icon' => 'fa-shopping-cart',
				'fields' => array(
					array('title' => __('Number of products per page', 'pukka'),
						'desc' => __('Select number of products to display per page in shop.', 'pukka'),
						'type' => 'select',
						'subtype' => 'range',
						'min' => 1,
						'max' => 50,
						'id' => 'products_per_page',
						'reset' => true,
						'default' => 16,
					),
					array('title' => __('Enable products share', 'pukka'),
						'desc' => __('Enable social media share buttons for products.', 'pukka'),
						'type' => 'checkbox',
						'id' => 'enable_product_share',
						'default' => 'on',
					),
				),
			), // end tab Shop
			array(
				'title' => __('Sidebars and Menus', 'pukka'),
				'icon' => '',
				'fields' => array(
					array('title' => __('Menu position', 'pukka'),
						'desc' => __('Select where to show menu', 'pukka'),
						'type' => 'select',
						'id' => 'main_menu_position',
						'options' => array('top' => 'Top', 'left' => 'Left'),
						'default' => 'top',
						'no_default_text' => true,
					),
					array('title' => __('Main menu type', 'pukka'),
					      'desc' => __('Choose menu behaviour. Note, this option applies only if "top" menu is selected', 'pukka'),
					      'type' => 'select',
					      'options' => array('regular' => __('Regular', 'pukka'), 'sticky' => __('Sticky', 'pukka')),
					      'default' => 'regular',
					      'id' => 'menu_type',
					      'no_default_text' => true,
					),
					array('title' => __('Show left sidebar', 'pukka'),
						'desc' => __('Enable left sidebar display. (Note: if you select "Left" for the Menu position, left sidebar will be shown regardless if this option is selected or not.)', 'pukka'),
						'type' => 'checkbox',
						'id' => 'sidebar_left_enable',
					),
					array('title' => __('Left sidebar width', 'pukka'),
						'desc' => __('This setting changes the width of the left sidebar.', 'pukka'),
						'type' => 'select',
						'subtype' => 'range',
						'id' => 'sidebar_left_width',
						'min' => 100,
						'max' => 500,
						'increment' => 5,
						'reset' => true,
						'default' => 190,
					),
					array('title' => __('Show right sidebar', 'pukka'),
						'desc' => __('Enable right sidebar display. ', 'pukka'),
						'type' => 'checkbox',
						'id' => 'sidebar_right_enable',
					),
					array('title' => __('Right sidebar width', 'pukka'),
						'desc' => __('This setting changes the width of the right sidebar.', 'pukka'),
						'type' => 'select',
						'subtype' => 'range',
						'id' => 'sidebar_right_width',
						'min' => 100,
						'max' => 500,
						'increment' => 5,
						'reset' => true,
						'default' => 250,
					),
				)
			), // end sidebars and menus
			array(
				'title' => __('Social', 'pukka'),
				'icon' => 'fa-users',
				'fields' => array(
					array('title' => __('Social buttons', 'pukka'),
						'type' => 'heading',
					),
					/*
					array('title' => __('Facebook Admins', 'pukka'),
						'desc' => __('FB IDevi korisnika', 'pukka'),
						'type' => 'text',
						'id' => 'facebook_admins',
					),
					*/
					array('title' => __('Facebook App ID', 'pukka'),
						'desc' => __('Insert your Facebook App ID. This means you now need to create a Facebook app to perform integration. <br /><br/ >Don\'t worry, creating an app is easy, you don\'t need to be a developer to create an app here. <br />Visit <a href="https://developers.facebook.com/apps/">https://developers.facebook.com/apps/</a> and click create new app.', 'pukka'),
						'type' => 'text',
						'id' => 'facebook_app_id',
					),
					array('title' => __('Enable Facebook Open Graph Tags', 'pukka'),
						'desc' => __('If you are using some other Social plugin, then you may want to disable this.', 'pukka'),
						'type' => 'checkbox',
						'id' => 'print_og_tags',
					),
					array('title' => __('Facebook like button', 'pukka'),
						'desc' => __('Add Facebook "Like" Button to Each Post/Page ', 'pukka'),
						'type' => 'checkbox',
						'id' => 'social_fb_like',
					),
					array('title' => __('Tweet button', 'pukka'),
						'desc' => __('Add Tweet Button to Each Post/Page', 'pukka'),
						'type' => 'checkbox',
						'id' => 'social_twitter',
					),
					array('title' => __('Google+ button', 'pukka'),
						'desc' => __('Add Google+ Button to Each Post/Page', 'pukka'),
						'type' => 'checkbox',
						'id' => 'social_gplus',
					),
					array('title' => __('LinkedIn button', 'pukka'),
						'desc' => __('Add LinkedIn Button to Each Post/Page', 'pukka'),
						'type' => 'checkbox',
						'id' => 'social_linkedin',
					),
					array('title' => __('Pinterest button', 'pukka'),
						'desc' => __('Add Pinterest Button to Each Post/Page', 'pukka'),
						'type' => 'checkbox',
						'id' => 'social_pinterest',
					),
					/*
					array('title' => __('Disable social buttons on Pages', 'pukka'),
						'desc' => __('Choose this option in order to disable social buttons on Pages.', 'pukka'),
						'type' => 'checkbox',
						'id' => 'page_disable_share',
					),
					*/
					array('title' => __('Add links to your Social Networks', 'pukka'),
						'type' => 'heading',
					),
					array('title' => __('Social icons position', 'pukka'),
						'desc' => __('Select where do you want to show your social icons', 'pukka'),
						'type' => 'select',
						'multiple' => 3,
						'no_default_text' => true,
						'id' => 'social_icons_position',
						'options' => array('top-menu' => 'in Top menu', 'footer-menu' => 'in Footer menu'),
						// 'reset' => true,
					),
					array('title' => __('Facebook URL', 'pukka'),
						'desc' => __('Facebook Fan Page URL.', 'pukka'),
						'type' => 'text',
						'id' => 'facebook_url',
					),
					array('title' => __('Twitter URL', 'pukka'),
						'desc' => __('Twitter account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'twitter_url',
					),
					array('title' => __('Google+ URL', 'pukka'),
						'desc' => __('Google+ account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'gplus_url',
					),
					array('title' => __('Youtube URL', 'pukka'),
						'desc' => __('Youtube account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'youtube_url',
					),
					array('title' => __('Soundcloud URL', 'pukka'),
						'desc' => __('Soundcloud account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'soundcloud_url',
					),
					array('title' => __('Vimeo URL', 'pukka'),
						'desc' => __('Youtube account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'vimeo_url',
					),
					array('title' => __('LinkedIn URL', 'pukka'),
						'desc' => __('LinkedIn account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'linkedin_url',
					),
					array('title' => __('Pinterest URL', 'pukka'),
						'desc' => __('Pinterest account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'pinterest_url',
					),
					array('title' => __('Instagram URL', 'pukka'),
						'desc' => __('Instagram account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'instagram_url',
					),
					array('title' => __('Tumblr URL', 'pukka'),
						'desc' => __('Tumblr account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'tumblr_url',
					),
					array('title' => __('Flickr URL', 'pukka'),
						'desc' => __('Flickr account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'flickr_url',
					),
					array('title' => __('Dribbble URL', 'pukka'),
						'desc' => __('Dribbble account URL.', 'pukka'),
						'type' => 'text',
						'id' => 'dribbble_url',
					),
					array('title' => __('RSS URL', 'pukka'),
						'desc' => __('RSS URL.', 'pukka'),
						'type' => 'text',
						'id' => 'rss_url',
					),
					array('title' => __('Custom icons', 'pukka'),
						'desc' => __('You can add your custom icons here, for example: <br /> &lt;a target=&quot;_blank&quot; href=&quot;YOUR_URL&quot;&gt;&lt;img src=&quot;ICON_URL&quot; width=&quot;15&quot; height=&quot;15&quot; /&gt;&lt;/a&gt;', 'pukka'),
						'type' => 'textarea',
						'id' => 'custom_social_links',
					),
				),
			), // end tab Social
			array(
				'title' => __('Style', 'pukka'),
				'icon' => 'fa-pencil',
				'fields' => array(
					/*
					array('title' => __('Theme color scheme', 'pukka'),
						'desc' => __('You can change entire theme color scheme here.', 'pukka'),
						'type' => 'select',
						'id' => PUKKA_THEME_COLORSCHEME_NAME,
						'options' => $color_schemes,
						'no_default_text' => true,
						'reset' => true,
						'default' => 'none',
					),
					*/
					array('title' => __('Primary Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'theme_primary_color',
						'default' => '#0871A3',
						'reset' => true,
						'css_classes' => 'two-cols input-short'
					),					
					array('title' => __('Secondary Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'theme_secondary_color',
						'default' => '#76AFCC',
						'reset' => true,
					),
					array('title' => __('Custom CSS', 'pukka'),
						'desc' => __('If you have some CSS changes enter them here or use the custom .css file', 'pukka'),
						'type' => 'textarea',
						'id' => 'custom_css',
					),
					array('title' => __('Custom JS', 'pukka'),
						'desc' => __('If you have some JS that you want to add, you can add it here. Do not surround your code with &lt;script&gt; tags, it will brake the code.', 'pukka'),
						'type' => 'textarea',
						'id' => 'custom_js',
					),
				),
			), // end tab Style
			array(
				'title' => __('Typography', 'pukka'),
				'icon' => 'fa-font',
				'fields' => array(

					array('title' => __('Title font', 'pukka'),
						'desc' => __('Title font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'title_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'title_font_size',
						'default' => 36,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'title_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),					
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'title_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'title_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),

					array('title' => __('Text font', 'pukka'),
						'desc' => __('Text font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'text_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'text_font_size',
						'default' => 14,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'text_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'text_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'text_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),

					array('title' => __('H1 font', 'pukka'),
						'desc' => __('H1 font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'h1_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'h1_font_size',
						'default' => 28,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'h1_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'h1_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'h1_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),

					array('title' => __('H2 font', 'pukka'),
						'desc' => __('H2 font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'h2_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'h2_font_size',
						'default' => 24,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'h2_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'h2_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'h2_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),


					array('title' => __('H3 font', 'pukka'),
						'desc' => __('H3 font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'h3_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'h3_font_size',
						'default' => 18,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'h3_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'h3_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'h3_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),


					array('title' => __('H4 font', 'pukka'),
						'desc' => __('H1 font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'h4_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'h4_font_size',
						'default' => 16,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'h4_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'h4_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'h4_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),

					array('title' => __('H5 font', 'pukka'),
						'desc' => __('H5 font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'h5_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'h5_font_size',
						'default' => 14,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'h5_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'h5_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'h5_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),

					array('title' => __('H6 font', 'pukka'),
						'desc' => __('H6 font description (color and size not implemented)', 'pukka'),
						'type' => 'section-open',
					),
					array('title' => __('Font', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => $fonts,
						'reset' => true,
						'id' => 'h6_font',
					),
					array('title' => __('Size', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'subtype' => 'range',
						'min' => 5,
						'max' => 80,
						'increment' => 1,
						'id' => 'h6_font_size',
						'default' => 12,
						'reset' => true,
						'css_classes' => 'half-size',
					),
					array('title' => __('Weight', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'options' => array('100' => '100', '200' => '200', '300' => '300', '400' => '400', '500' => '500', '600' => '600', '700' => '700', '800' => '800'),
						'id' => 'h6_font_weight',
						'default' => '500',
						'reset' => true,
						'css_classes' => 'half-size',
						'no_default_text' => true,
					),
					array('title' => __('Font Effect', 'pukka'),
						'desc' => '',
						'type' => 'select',
						'id' => 'h5_font_effect',
						'options' => $font_effects,
						'reset' => true,
					),
					array('title' => __('Color', 'pukka'),
						'desc' => '',
						'type' => 'color-picker',
						'id' => 'h6_font_color',
						'default' => '#666666',
						'reset' => true,
						'css_classes' => ''
					),
					array('title' => '',
						'desc' => '',
						'type' => 'section-close',
					),
					array('title' => __('Add cyrillic character set', 'pukka'),
						'desc' => __('Choose this option to enable cyrillic characters in you google fonts. (Note that not all google fonts support cyrillic character set)', 'pukka'),
						'type' => 'checkbox',
						'id' => 'enable_cyrillic_char_set',
						'reset' => true,
					),
					array('title' => __('Custom Fonts', 'pukka'),
						'desc' => __('If you have some additional fonts that you would like tu use paste your code here, for example:<br />' . esc_html("<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>"), 'pukka'),
						'type' => 'textarea',
						'id' => 'custom_fonts',
					),
				),
			), // end tab Typography
			array(
				'title' => __('Forms', 'pukka'),
				'icon' => 'fa-files-o',
				'fields' => array(
					array('title' => __('Email', 'pukka'),
						'desc' => __('Add your email address here. All emails from custom Forms (Page Builder) will be sent to this address.', 'pukka'),
						'type' => 'text',
						'id' => 'form_email',
					),
					array('title' => __('Thank you notification', 'pukka'),
						'desc' => __('Insert text for your "Thank You" page here. For example: Thanks for getting in touch! We\'ll reach out to you within 24 hours either by phone or email!.', 'pukka'),
						'type' => 'text',
						'id' => 'form_thank_you',
					),
					array('title' => __('Error notification', 'pukka'),
						'desc' => __('Add text that will be displayed in case error occurred during form submission.', 'pukka'),
						'type' => 'text',
						'id' => 'form_error',
					),
					array('title' => 'SPAM check',
								'desc' => 'Enter 4 comma separated numbers here, between 1 and 10, to enable spam check for your contact forms (for example: 1,3,5,9)',
								'type' => 'text',
								'id' => 'form_spam_numbers',
					),
					array('title' => __('Google Map API key', 'pukka'),
						'desc' => __('You can generate API key by following <a href="https://developers.google.com/maps/documentation/javascript/get-api-key#key" target="_blank" rel="noopener">this steps</a>.', 'pukka'),
						'type' => 'text',
						'id' => 'google_map_api_key',
					),
				),
			), // end tab Forms
			array(
				'title' => __('Widget areas', 'pukka'),
				'icon' => '',
				'fields' => array(
					array('title' => __('Custom widget areas', 'pukka'),
						'desc' => __('Add your widget area.', 'pukka'),
						'type' => 'dynamic-input',
						'id' => 'custom_widget_areas',
					),
				)
			), // end tab Widgets
			array(
				'title' => __('Portfolio', 'pukka'),
				'icon' => '',
				'fields' => array(
					array('title' => __('Number of portfolio items per row', 'pukka'),
						'desc' => __('Number of portfolio items per row for archive pages.', 'pukka'),
						'type' => 'select',
						'subtype' => 'range',
						'min' => 2,
						'max' => 6,
						'id' => 'portfolio_col_no',
						'reset' => true,
						'default' => 1,
					),
					array('title' => __('Don\'t use margins', 'pukka'),
						'desc' => __('Don\'t use margins', 'pukka'),
						'type' => 'checkbox',
						'id' => 'portfolio_no_margins',
					),
				),
			), // end tab Portfolio
			array(
				'title' => __('Content importer', 'pukka'),
				'icon' => 'fa-exclamation-circle',
				'fields' => array(
					array('title' => __('Pukka demo content importer', 'pukka'),
						'desc' => __('This is importer for theme demo content. Please only use it on fresh WordPress installs with empty database. Otherwise, results might be somewhat unexpected.', 'pukka'),
						'type' => 'custom-html',
						'content' => '<div class="import-controls">
										<img class="waiting" id="waiting-import" style="display:none;" src="' . admin_url('images') . '/wpspin_light.gif" alt="" />
										<div class="pukka-button-primary" id="pukka-import">Start import</div>
									</div>
									<div id="pukka-import-frame"></div>'
					)
				),
			), // end tab Forms
		) // close tabs
	);

	return $pukka_theme_option_pages;
}
