<?php
/**
 * Sidebars configuration.
 *
 * @package Solosshopy
 */

add_action( 'after_setup_theme', 'solosshopy_register_sidebars', 5 );
/**
 * Register sidebars.
 */
function solosshopy_register_sidebars() {

	solosshopy_widget_area()->widgets_settings = apply_filters( 'solosshopy_widget_area_default_settings', array(
		'sidebar' => array(
			'name'           => esc_html__( 'Sidebar', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<div id="%1$s" %2$s role="complementary">',
			'after_wrapper'  => '</div>',
			'is_global'      => true,
		),
		'shop-sidebar' => array(
			'name'           => esc_html__( 'Single Product Sidebar', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<div id="%1$s" %2$s role="complementary">',
			'after_wrapper'  => '</div>',
			'is_global'      => true,
		),
		'full-width-header-area' => array(
			'name'           => esc_html__( 'Header Fullwidth Area', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<section id="%1$s" %2$s>',
			'after_wrapper'  => '</section>',
			'is_global'      => false,
			'conditional'    => array( 'is_home' ),
		),
		'before-content-area' => array(
			'name'           => esc_html__( 'Before Content Area', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<section id="%1$s" %2$s>',
			'after_wrapper'  => '</section>',
			'is_global'      => false,
			'conditional'    => array( 'is_home' ),
		),
		'before-loop-area' => array(
			'name'           => esc_html__( 'Before Loop Area', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<section id="%1$s" %2$s>',
			'after_wrapper'  => '</section>',
			'is_global'      => false,
			'conditional'    => array( 'is_home' ),
		),
		'after-loop-area' => array(
			'name'           => esc_html__( 'After Loop Area', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<section id="%1$s" %2$s>',
			'after_wrapper'  => '</section>',
			'is_global'      => false,
			'conditional'    => array( 'is_home' ),
		),
		'after-content-area' => array(
            'name'           => esc_html__( 'After Content Area', 'solosshopy' ),
            'description'    => '',
            'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
            'after_widget'   => '</aside>',
            'before_title'   => '<h5 class="widget-title">',
            'after_title'    => '</h5>',
            'before_wrapper' => '<section id="%1$s" %2$s>',
            'after_wrapper'  => '</section>',
            'is_global'      => false,
            'conditional'    => array( 'is_home' ),
        ),
        'after-content-custom-area' => array(
            'name'           => esc_html__( 'After Content Custom Area', 'solosshopy' ),
            'description'    => '',
            'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
            'after_widget'   => '</aside>',
            'before_title'   => '<h5 class="widget-title">',
            'after_title'    => '</h5>',
            'before_wrapper' => '<section id="%1$s" %2$s><div class="container">',
            'after_wrapper'  => '</div></section>',
            'is_global'      => true,
        ),
        'after-content-second-custom-area' => array(
            'name'           => esc_html__( 'After Content Second Custom Area', 'solosshopy' ),
            'description'    => '',
            'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
            'after_widget'   => '</aside>',
            'before_title'   => '<h5 class="widget-title">',
            'after_title'    => '</h5>',
            'before_wrapper' => '<section id="%1$s" %2$s><div class="container">',
            'after_wrapper'  => '</div></section>',
            'is_global'      => true,
        ),
		'after-content-full-width-area' => array(
			'name'           => esc_html__( 'After Content Fullwidth Area', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<section id="%1$s" %2$s>',
			'after_wrapper'  => '</section>',
			'is_global'      => true,
		),
		'footer-area' => array(
			'name'           => esc_html__( 'Footer Area', 'solosshopy' ),
			'description'    => '',
			'before_widget'  => '<aside id="%1$s" class="widget %2$s">',
			'after_widget'   => '</aside>',
			'before_title'   => '<h5 class="widget-title">',
			'after_title'    => '</h5>',
			'before_wrapper' => '<section id="%1$s" %2$s>',
			'after_wrapper'  => '</section>',
			'is_global'      => true,
		),
	) );
}
